// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: call.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallServiceClient interface {
	InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	CallStream(ctx context.Context, opts ...grpc.CallOption) (CallService_CallStreamClient, error)
}

type callServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallServiceClient(cc grpc.ClientConnInterface) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) InitiateCall(ctx context.Context, in *InitiateCallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/call.CallService/InitiateCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) CallStream(ctx context.Context, opts ...grpc.CallOption) (CallService_CallStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &CallService_ServiceDesc.Streams[0], "/call.CallService/CallStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &callServiceCallStreamClient{stream}
	return x, nil
}

type CallService_CallStreamClient interface {
	Send(*CallSignal) error
	Recv() (*CallSignal, error)
	grpc.ClientStream
}

type callServiceCallStreamClient struct {
	grpc.ClientStream
}

func (x *callServiceCallStreamClient) Send(m *CallSignal) error {
	return x.ClientStream.SendMsg(m)
}

func (x *callServiceCallStreamClient) Recv() (*CallSignal, error) {
	m := new(CallSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CallServiceServer is the server API for CallService service.
// All implementations must embed UnimplementedCallServiceServer
// for forward compatibility
type CallServiceServer interface {
	InitiateCall(context.Context, *InitiateCallRequest) (*CallResponse, error)
	CallStream(CallService_CallStreamServer) error
	mustEmbedUnimplementedCallServiceServer()
}

// UnimplementedCallServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCallServiceServer struct {
}

func (UnimplementedCallServiceServer) InitiateCall(context.Context, *InitiateCallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateCall not implemented")
}
func (UnimplementedCallServiceServer) CallStream(CallService_CallStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CallStream not implemented")
}
func (UnimplementedCallServiceServer) mustEmbedUnimplementedCallServiceServer() {}

// UnsafeCallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallServiceServer will
// result in compilation errors.
type UnsafeCallServiceServer interface {
	mustEmbedUnimplementedCallServiceServer()
}

func RegisterCallServiceServer(s grpc.ServiceRegistrar, srv CallServiceServer) {
	s.RegisterService(&CallService_ServiceDesc, srv)
}

func _CallService_InitiateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).InitiateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/call.CallService/InitiateCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).InitiateCall(ctx, req.(*InitiateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_CallStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CallServiceServer).CallStream(&callServiceCallStreamServer{stream})
}

type CallService_CallStreamServer interface {
	Send(*CallSignal) error
	Recv() (*CallSignal, error)
	grpc.ServerStream
}

type callServiceCallStreamServer struct {
	grpc.ServerStream
}

func (x *callServiceCallStreamServer) Send(m *CallSignal) error {
	return x.ServerStream.SendMsg(m)
}

func (x *callServiceCallStreamServer) Recv() (*CallSignal, error) {
	m := new(CallSignal)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CallService_ServiceDesc is the grpc.ServiceDesc for CallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "call.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateCall",
			Handler:    _CallService_InitiateCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallStream",
			Handler:       _CallService_CallStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "call.proto",
}
